### ISSUE TITLE
not able to switch between windows when I have more than 1 instance of the same app

### ISSUE THREAD

**Issue by molitona** [dsheeler/CoverflowAltTab#190]
Hi, recently I was not able to switch between windows when I have more than 1 instance of the same app.

For example if I opened file manager or Firefox 2 times then i can't switch between the 2 instances of them with ALT+TAB.

I use Gnome 43.2 with latest extension of this extension.
The weird thing that it was switching fine between more than 1 instance of the same app for almost 2 years. And stopped working from 3 days (i haven't updated my Arch OS, neither done anything).

Also, notice on video somehow one window gets into some other (it's happened only this time when i encountered this problem, not the case in the past too)

https://user-images.githubusercontent.com/35532337/214840732-6aec68c1-d5d3-40aa-801d-580ed55b4f82.mp4

**Comment by dsheeler** [comment]
Hi @molitona, this is a feature, not a bug. This is a new "application switcher" mode that gets invoked when you use the switch-applications keybinding action which is normally bound to Super-Tab. The behavior you expect still works when you use the switch-windows action which is normally bound to Alt-Tab. In fact, I didn't anticipate your situation because I thought everyone was using Alt-Tab! 

When you get to an application with multiple windows, now you get a sub-switcher which you can cycle through by hitting arrows or scrolling with the mouse.  Let me know what you think of it, please.  I mostly tried to mimic the behaviour of built-in gnome-shell application switcher which jumps from application to application on Super-Tab even when an application has multiple windows-- cycling through the multiple windows of an application requires mouse scrolling or arrow keys.

I can make this functionality optional... like I said, I thought most people would be using Alt-Tab to invoke Coverflow *Alt-Tab* haha. Let me know what you think!

**Comment by dsheeler** [comment]
See also #189

**Comment by molitona** [comment]
Hi @dsheeler,

Now I get it. Switching using a sub-switcher is always there using ALT+TAB or SUPER+TAB. 
In fact I run away from default gnome switching 'cause I don't open too much windows like I've max 10 window open.
So, how can I use it without sub-switcher (ALT+TAB or SUPER+TAB use sub-switcher)

**Comment by dsheeler** [comment]
@molitona: Go to gnome-settings / Keyboard / "View and Customize Shortcuts" / Navigation and set "Switch applications" to Super+Tab, and "Switch windows" to Alt+Tab.  That's how I have it.

**Comment by molitona** [comment]
thanks a lot!!
