### ISSUE TITLE
Last to first animation

### ISSUE THREAD

**Issue by ai** [dsheeler/CoverflowAltTab#23]
I have 3 window, I press `Alt+Tab` and teh `Tab` 2 times and when I switch from last app in list to first one, there is very strange animation.

Now last to first animation look like I swtich from workplasces (because app list is fly to left and “some new” list fly from right).

**Comment by doncullen** [comment]
As tinypic only uses Flash to show videos -- Chrome no longer displays those -- tinypic isn't the best site to use at the moment.  Since I can't see the videos, I'm going to just guess at what was referenced. 

The default behavior is for it to keep switching to the last window while tab is pressed repeatedly as alt is held.  Once the last window is reached, it then goes back to the first window.  This seems a bit disruptive -- the whole point of cover flow is a continuous flow.  Expected behavior would be infinity-flow style.  Instead of abruptly going back to the start of the cover flow, would be best to simply "append" the start to the end, thus resulting in an infinite loop. 

Being a web developer, I was able to find something that behaves somewhat similarly:  https://codepen.io/shshaw/pen/NxWgxJ?editors=001

Hope that helps to give a better picture of the ideal behavior.  One could always implement an option for user to pick their preferred behavior (non-looped vs looped).
